apiVersion: v1
kind: Secret
metadata:
  name: secret-postgresql-connection
type: kubernetes.io/Opaque
stringData:
  # in the format postgresql://user:password@hostname:port/database_name
  # must match values supplied to postgresql.auth in values.yaml
  connectionString: postgresql://postgres:root@deeplynx-postgres:5432/deep_lynx_dev

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-redis-connection
type: kubernetes.io/Opaque
stringData:
  # in the format redis://user:password@redis-service.com:6379/ (user may be blank for the default user)
  # must match values supplied to redis.auth in values.yaml
  connectionString: redis://:root@deeplynx-redis:6379/
