import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/app/_components/sidebar"
import { ThemeProvider }  from "@/app/_components/theme-provider"

import clsx from 'clsx'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// THIS LAYOUT IS FOR THE AUTH PAGE AFTER REACHING THE LANDING PAGE

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const prefersDark = cookies().get('x-theme')?.value === 'dark'
    return (


        <html lang="en">
          <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>

          <Sidebar />
          {children}
          </ThemeProvider>

          </body>
        </html>
    );
}
