import Config

# Configure your database
config :datum, Datum.Repo,
  database: Path.join([System.user_home(), "/.datum_databases", "operations.db"]),
  journal_mode: :wal,
  auto_vacuum: :incremental,
  datetime_type: :iso8601,
  load_extensions: [
    "./priv/sqlite_extensions/crypto",
    "./priv/sqlite_extensions/fileio",
    "./priv/sqlite_extensions/fuzzy",
    "./priv/sqlite_extensions/math",
    "./priv/sqlite_extensions/stats",
    "./priv/sqlite_extensions/text",
    "./priv/sqlite_extensions/unicode",
    "./priv/sqlite_extensions/uuid",
    "./priv/sqlite_extensions/vec0",
    "./priv/sqlite_extensions/vsv"
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :datum, DatumWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "wxlPJjJbd4NPxfcAjS8f1CrK4OmeEzOiGLygZ69Ty1SKcq+GkpCU67hl7w6FiDMG",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:datum, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:datum, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :datum, DatumWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/datum_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :datum, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# we use openAI compatible agents - this way we can hook up to the service
# OR more likely, to Ollama or another locally running model with openAI
# compatible specs - by default it talks to ollama and the model that INL
# has an agreement to use
config :datum,
  openai_enabled: true,
  openai_endpoint: "http://localhost:11434/v1/chat/completions",
  openai_key: "ollama",
  openai_model: "llama3.2",
  openai_temp: 1
