name: Build Image
on:
  workflow_dispatch:


jobs:
  build-deeplynx-docker:
    runs-on: [ self-hosted ]
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: deeplynx
          ref: development

      - shell: bash
        name: ACR build deeplynx
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          cd $GITHUB_WORKSPACE/deeplynx
          az cloud set --name AzureUSGovernment
          az login --service-principal -u $ACR_SP_USER -p $ACR_SP_PASSWORD --tenant $ACR_SP_TENANT
          az account set --subscription $ACR_SUBSCRIPTION
          az acr build -r $ACR_REGISTRY -f $GITHUB_WORKSPACE/server/legacy/Dockerfile -t $ACR_PATH:$GITHUB_SHA-manual .
