# create this in .github/workflows/ci.yml
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CI: true
  MIX_ENV: "prod"

  
permissions:
  contents: write

jobs:
  precompile:
    runs-on: ${{ matrix.os }}
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} / OS ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        otp: ['27.2.1']
        elixir: ['1.18.2']
        rebar3: ['3.24.0']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
